public enum Controls{
	LOOK_X = 0,
	LOOK_Y,
	STRAFE_X,
	STRAFE_Y,
	ROLL,
	THROTTLE,
	HEADTURN_X,
	HEADTURN_Y,


	// any additional analog controls must be added above this line!
	FIRE,
	ALT_FIRE,
	DAMPENERS,
	BOOST,
	RADAR_BUTTON,
	CAMERA_BUTTON,
	PAUSE_BUTTON,
	TARGET_BUTTON,
	NEXT_WEAPON,
	PREVIOUS_WEAPON,
	SELECT_WEAPON_1,
	SELECT_WEAPON_2,
	SELECT_WEAPON_3,
	SELECT_WEAPON_4,
	HEADTURN,
	QUICKTURN,
	/*MENU_UP,
	MENU_DOWN,
	MENU_LEFT,
	MENU_RIGHT,
	MENU_CONFIRM,
	MENU_CANCEL,
	MENU_NEXTPAGE,
	MENU_PREVIOUSPAGE,
	MENU_NEXTTAB,
	MENU_PREVIOUSTAB,*/

	//any additional digital controls must be added between this line and Controls.FIRE!
	NUMBER_OF_CONTROLS
}
